import { Inter } from "@next/font/google";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

type props = {
  children: React.ReactNode;
};

function Layout({ children }: props): JSX.Element {
  return (
    <>
      <Head>
        <title>Cart System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
}

export default Layout;
