import { Inter } from "@next/font/google";
import Head from "next/head";
import Product from "../components/Products";
import RelatedItems from "../components/RelatedItems";
import Subtotal from "../components/Subtotal";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

type props = {
  children: React.ReactNode;
};

export default function Home({ children }: props) {
  return (
    <>
      <Head>
        <title>Cart System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.productList}>
          <Product />
        </div>
        <div className={styles.subTotalAndRelated}>
          <Subtotal />
          <RelatedItems />
        </div>
      </main>
    </>
  );
}
